{% set name = "PySimpleGUIQt" %}
{% set version = "0.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c18ea261554235a2cdaee76e616d0adc148501e89bf4112a798f2a69bf3c8b5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyside2

test:
  requires:
    - python {{ python_min }}
  imports:
    - PySimpleGUIQt

about:
  home: https://github.com/PySimpleGUI/PySimpleGUI
  license: LGPL-3.0
  license_family: LGPL
  license_file: license.txt
  description: GUI SDK Launched in 2018 Actively developed and supported. Super-simple to create custom GUI's.  Python 2.7 & 3 Support. 100 Demo programs & Cookbook for rapid start. Extensive documentation. Examples using Machine Learning(GUI, OpenCV Integration,  Chatterbot), Rainmeter Style Floating Desktop Widgets, Matplotlib
    + Pyplot integration, add GUI to command line scripts, PDF & Image Viewer. Great for beginners as well as advanced GUI programmers
  summary: GUI SDK Launched in 2018 Actively developed and supported.
  doc_url: http://www.pysimplegui.org/
  dev_url: https://github.com/PySimpleGUI/PySimpleGUI

extra:
  recipe-maintainers:
    - silun
